#pragma once
#include <iostream>
#include <functional>
#include <utility>
#include <vector>
#include <string>
#include <tuple>
#include <map>
using std::vector;
using std::string;
using std::ostream;
using std::pair;
using std::function;
using std::map;
using std::tuple;
using std::max;
#ifdef _WIN32
#include <windows.h>
#endif